[package]
name = "audio_feed"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.26"
futures = "0.3"
log = "0.4"
env_logger = "0.11"
cpal = "0.15.3"
