name: Build

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 4 14,28 * *"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Base Image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: base
          platforms: linux/amd64,linux/arm64
          push: true
          tags: lesvu/vn_vnc:base

      - name: Build and push Hangover Image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: hangover
          platforms: linux/arm64
          push: true
          tags: lesvu/vn_vnc:hangover
